# Generated by Django 5.2.8 on 2025-11-24 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGUARDANDO_CONFIRMACAO', 'Aguardando Confirmação'), ('ACEITO', 'Aceito'), ('EM_PRODUCAO', 'Em Produção'), ('LIBERADO', 'Liberado'), ('PAGO', 'Pago')], default='AGUARDANDO_CONFIRMACAO', max_length=25, verbose_name='Status')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('delivery_street', models.CharField(max_length=255, verbose_name='Rua')),
                ('delivery_number', models.CharField(max_length=10, verbose_name='Número')),
                ('delivery_complement', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('delivery_neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('delivery_city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('delivery_state', models.CharField(max_length=2, verbose_name='Estado')),
                ('delivery_zipcode', models.CharField(max_length=9, verbose_name='CEP')),
                ('observations', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('alterable_until', models.DateTimeField(blank=True, null=True, verbose_name='Alterável até')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Código')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('attempts', models.IntegerField(default=0, verbose_name='Tentativas')),
                ('validated', models.BooleanField(default=False, verbose_name='Validado')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validado em')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_code', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Código de Entrega',
                'verbose_name_plural': 'Códigos de Entrega',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('PRODUCT', 'Produto Pronto'), ('CUSTOM_CUPCAKE', 'Cupcake Personalizado')], max_length=15, verbose_name='Tipo de Produto')),
                ('custom_cupcake_data', models.JSONField(blank=True, help_text='JSON com massa_id, recheio_id, cobertura_id', null=True, verbose_name='Dados do Cupcake Personalizado')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
    ]
