# Generated by Django 5.2.8 on 2025-11-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_CONFIRMACAO', 'Aguardando Confirmação'), ('ACEITO', 'Aceito'), ('EM_PRODUCAO', 'Em Produção'), ('LIBERADO', 'Liberado'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_CONFIRMACAO', max_length=25, verbose_name='Status'),
        ),
    ]
