# Generated by Django 5.0.1 on 2025-12-12 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('orders', '0002_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='assigned_operator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'OPERATOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Operador Atribuído'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Obrigatório para conversas Cliente-Estabelecimento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='orders.order', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('open', 'Aberta'), ('resolved', 'Resolvida'), ('closed', 'Fechada')], default='open', max_length=10, verbose_name='Status'),
        ),
    ]
