# Generated by Django 5.2.8 on 2025-11-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CupcakeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MASSA', 'Massa'), ('RECHEIO', 'Recheio'), ('COBERTURA', 'Cobertura')], max_length=10, verbose_name='Tipo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cupcake_components/', verbose_name='Imagem')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Componente de Cupcake',
                'verbose_name_plural': 'Componentes de Cupcake',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem')),
                ('category', models.CharField(choices=[('CUPCAKE', 'Cupcake Pronto'), ('BOLO', 'Bolo'), ('DOCE', 'Doce'), ('OUTROS', 'Outros')], default='CUPCAKE', max_length=10, verbose_name='Categoria')),
                ('stock', models.IntegerField(default=0, verbose_name='Estoque')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
    ]
