import { useState, useEffect } from 'react';
import { Layout } from '../components/Layout/Layout';
import { useAuthStore } from '../store/authStore';
import { viaCepApi, addressApi } from '../services/api';
import type { Address } from '../types';
import { HiPlus, HiTrash } from 'react-icons/hi';

export const Profile = () => {
  const { user } = useAuthStore();
  const [addresses, setAddresses] = useState<Address[]>([]);
  const [showAddressForm, setShowAddressForm] = useState(false);
  const [loading, setLoading] = useState(false);
  const [newAddress, setNewAddress] = useState({
    cep: '',
    street: '',
    number: '',
    district: '',
    city: '',
    state: '',
  });

  useEffect(() => {
    loadAddresses();
  }, []);

  const loadAddresses = async () => {
    try {
      const data = await addressApi.getAll();
      setAddresses(data);
    } catch (error) {
      console.error('Erro ao carregar endereços:', error);
    }
  };

  const handleCepBlur = async () => {
    if (newAddress.cep.length >= 8) {
      setLoading(true);
      try {
        const data = await viaCepApi.getByCep(newAddress.cep);
        if (!data.erro) {
          setNewAddress({
            ...newAddress,
            street: data.logradouro,
            district: data.bairro,
            city: data.localidade,
            state: data.uf,
          });
        }
      } catch (error) {
        console.error('Erro ao buscar CEP:', error);
      } finally {
        setLoading(false);
      }
    }
  };

  const handleAddAddress = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      await addressApi.create({
        ...newAddress,
        id: '', // Will be generated by backend
      });
      await loadAddresses();
      setNewAddress({
        cep: '',
        street: '',
        number: '',
        district: '',
        city: '',
        state: '',
      });
      setShowAddressForm(false);
    } catch (error) {
      console.error('Erro ao adicionar endereço:', error);
      alert('Erro ao adicionar endereço');
    } finally {
      setLoading(false);
    }
  };

  const handleDeleteAddress = async (id: string) => {
    if (confirm('Deseja realmente excluir este endereço?')) {
      try {
        await addressApi.delete(id);
        await loadAddresses();
      } catch (error) {
        console.error('Erro ao excluir endereço:', error);
        alert('Erro ao excluir endereço');
      }
    }
  };

  return (
    <Layout title="Perfil">
      <div className="space-y-6 py-4">
        {/* User Info */}
        <div className="bg-cake-cyan rounded-2xl shadow-lg p-6">
          <h2 className="text-xl font-semibold mb-4">Perfil</h2>
          <div className="space-y-3">
            <div>
              <label className="block text-sm font-medium mb-1">Nome:</label>
              <input
                type="text"
                value={user?.name || ''}
                readOnly
                className="w-full px-4 py-2 bg-white rounded-lg border-0"
              />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">E-mail ou telefone:</label>
              <input
                type="text"
                value={user?.email || ''}
                readOnly
                className="w-full px-4 py-2 bg-white rounded-lg border-0"
              />
            </div>
          </div>
        </div>

        {/* Addresses */}
        <div className="bg-cake-cyan rounded-2xl shadow-lg p-6">
          <h2 className="text-xl font-semibold mb-4">Endereços</h2>
          
          <div className="space-y-4">
            {addresses.map((address) => (
              <div
                key={address.id}
                className="bg-white rounded-lg p-4 relative"
              >
                <button
                  onClick={() => handleDeleteAddress(address.id)}
                  className="absolute top-2 right-2 p-2 text-red-500 hover:bg-red-50 rounded-lg"
                  aria-label="Excluir"
                >
                  <HiTrash size={18} />
                </button>
                <div className="grid grid-cols-2 gap-2 text-sm">
                  <div>
                    <span className="font-medium">CEP:</span> {address.cep}
                  </div>
                  <div>
                    <span className="font-medium">Número:</span> {address.number}
                  </div>
                  <div className="col-span-2">
                    <span className="font-medium">Endereço:</span> {address.street}
                  </div>
                  <div>
                    <span className="font-medium">Bairro:</span> {address.district}
                  </div>
                  <div>
                    <span className="font-medium">Cidade:</span> {address.city}
                  </div>
                  <div className="col-span-2">
                    <span className="font-medium">UF:</span> {address.state}
                  </div>
                </div>
              </div>
            ))}
          </div>

          {showAddressForm ? (
            <form onSubmit={handleAddAddress} className="mt-4 space-y-3">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-sm font-medium mb-1">CEP:</label>
                  <input
                    type="text"
                    value={newAddress.cep}
                    onChange={(e) =>
                      setNewAddress({ ...newAddress, cep: e.target.value })
                    }
                    onBlur={handleCepBlur}
                    className="w-full px-3 py-2 bg-white rounded-lg border-0"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium mb-1">Número:</label>
                  <input
                    type="text"
                    value={newAddress.number}
                    onChange={(e) =>
                      setNewAddress({ ...newAddress, number: e.target.value })
                    }
                    className="w-full px-3 py-2 bg-white rounded-lg border-0"
                    required
                  />
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Endereço:</label>
                <input
                  type="text"
                  value={newAddress.street}
                  onChange={(e) =>
                    setNewAddress({ ...newAddress, street: e.target.value })
                  }
                  className="w-full px-3 py-2 bg-white rounded-lg border-0"
                  required
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Bairro:</label>
                <input
                  type="text"
                  value={newAddress.district}
                  onChange={(e) =>
                    setNewAddress({ ...newAddress, district: e.target.value })
                  }
                  className="w-full px-3 py-2 bg-white rounded-lg border-0"
                  required
                />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-sm font-medium mb-1">Cidade:</label>
                  <input
                    type="text"
                    value={newAddress.city}
                    onChange={(e) =>
                      setNewAddress({ ...newAddress, city: e.target.value })
                    }
                    className="w-full px-3 py-2 bg-white rounded-lg border-0"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium mb-1">UF:</label>
                  <input
                    type="text"
                    value={newAddress.state}
                    onChange={(e) =>
                      setNewAddress({ ...newAddress, state: e.target.value })
                    }
                    maxLength={2}
                    className="w-full px-3 py-2 bg-white rounded-lg border-0"
                    required
                  />
                </div>
              </div>
              <div className="flex gap-2">
                <button
                  type="submit"
                  disabled={loading}
                  className="flex-1 bg-cake-pink hover:bg-cake-dark-pink text-cake-text font-semibold py-2 rounded-lg transition-colors disabled:opacity-50"
                >
                  {loading ? 'Salvando...' : 'Salvar'}
                </button>
                <button
                  type="button"
                  onClick={() => setShowAddressForm(false)}
                  className="flex-1 bg-gray-300 hover:bg-gray-400 text-cake-text font-semibold py-2 rounded-lg transition-colors"
                >
                  Cancelar
                </button>
              </div>
            </form>
          ) : (
            <button
              onClick={() => setShowAddressForm(true)}
              className="w-full mt-4 bg-white hover:bg-gray-50 text-cake-text font-semibold py-3 rounded-lg transition-colors flex items-center justify-center gap-2 border-2 border-dashed border-gray-300"
            >
              <HiPlus size={20} />
              Adicionar endereço
            </button>
          )}
        </div>
      </div>
    </Layout>
  );
};

